version: '3.9'
services:
  knowknow-ru:
    container_name: knowknow-crm
    image: knowknow-crm:latest
    volumes:
      - /usr/local/etc/knowknow-crm/:/var/www/html/application/config/
      - /var/local/knowknow-crm/files:/var/www/html/files
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8082:80"
