version: '3.9'
services:
  knowknow-api:
    container_name: knowknow-api
    image: knowknow-api:latest
    environment:
      NODE_ENV: production
    volumes:
      - /usr/local/etc/knowknow-api:/opt/knowknow-api/built/config
      - /var/local/knowknow-api:/opt/knowknow-api/public
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "4000:8080"
    networks:
      knowknow-pro:
        ipv4_address: 172.18.0.2
        
  knowknow-ui:
    container_name: knowknow-ui
    image: knowknow-ui:latest
    environment:
      API_ENDPOINT: 'https://school.knowknow.pro/api/graphql'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3000:3000"
    networks:
      knowknow-pro:
        ipv4_address: 172.18.0.3

  knowknow-pro:
    container_name: knowknow-pro
    image: knowknow-pro:latest
    environment:
      NUXT_PUBLIC_GQL_HOST: https://knowknow.pro/api/graphql
      NUXT_PUBLIC_BACKOFFICE_URI: https://school.knowknow.pro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3001:3000"
    networks:
      knowknow-pro:
        ipv4_address: 172.18.0.4

networks:
  knowknow-pro:
    driver: bridge
    ipam:
     config:
       - subnet: 172.18.0.0/16
         gateway: 172.18.0.1
