version: '3.9'
services:
  knowknow-api:
    image: knowknow-api:latest
    volumes:
      - /usr/local/etc/knowknow-api:/opt/knowknow-api/built/config
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "4000:8080"

  knowknow-ui:
    image: knowknow-ui:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      SERVER_LINK: 'http://knowknow-api:8080/api/graphql'
    ports:
      - "3000:3000"

  # knowknow-pro:
  #   image: knowknow-pro:latest
  #   environment:
  #   volumes:
  #   ports:
  #     - "3001:3000"
