version: '3.9'
services:
  knowknow-api:
    image: knowknow-api:latest
    volumes:
      - /usr/local/etc/knowknow-api:/opt/knowknow-api/built/config
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "4000:8080"
      
