name: Deploy CI

on:
  workflow_call:
    inputs:
      IMAGE_NAME:
        required: true
        type: string
      DEPLOY_NAME:
        required: true
        type: string
    secrets:
        DEPLOY_USER:
          required: true
        DEPLOY_PASS:
          required: true

jobs:
  autodeploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build project
      run: npm i; npm run build:dev

    - name: Build the Docker image
      run: docker build . --file Dockerfile -t ${{ inputs.IMAGE_NAME }}

    - name: Save the Docker image and gzip
      run: docker save ${{ inputs.IMAGE_NAME }} | gzip > ${{ inputs.IMAGE_NAME }}.tar.gz

    - name: Upload image file to remote server
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: ${{ vars.PROD_HOST }}
        port: ${{ vars.PROD_PORT }}
        username: ${{ secrets.DEPLOY_USER }}
        password: ${{ secrets.DEPLOY_PASS }}
        local_path: './${{ inputs.IMAGE_NAME }}.tar.gz'
        remote_path: './'
        sftp_only: true

    - name: Deploy
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ vars.PROD_HOST }}
        port: ${{ vars.PROD_PORT }}
        username: ${{ secrets.DEPLOY_USER }}
        password: ${{ secrets.DEPLOY_PASS }}
        script: |       
          sudo docker load < ./${{ inputs.IMAGE_NAME }}.tar.gz
          rm ./${{ inputs.IMAGE_NAME }}.tar.gz

          sudo docker compose -f /usr/local/etc/knowknow-deploy/docker-compose/${{inputs.DEPLOY_NAME }}.yaml up ${{ inputs.IMAGE_NAME }} -d

